version: 2

defaults: &defaults
  docker:
    - image: cszatma/swift:5.0
  working_directory: ~/SwiftSweetness

jobs:
  build-dev:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build package in debug mode.
          command: swift build
      - save_cache:
          key: swiftysweetness-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - .build/
  build-release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build package in release mode.
          command: swift build -c release
  lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install tools with mint
          command: mint bootstrap
      - run:
          name: Run swiftlint
          command: mint run swiftlint
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - swiftysweetness-build-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Run tests.
          command: swift test


workflows:
  version: 2
  build-test:
    jobs:
      - build-dev
      - build-release
      - lint
      - test:
          requires:
            - build-dev
